---
title: "Reproducible research PRCJ2"
author: "RH"
date: "October 27, 2016"
output: html_document
---

##Synopsis

##Data Processing
```{r data_proc, echo=TRUE, cache=TRUE}
  data_raw <- read.csv("repdata%2Fdata%2FStormData.csv.bz2")
  library(ggplot2)
```

##Question 1: Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?

```{r plot_fatalities, echo=TRUE, cache=TRUE}
  data_fatalities <- aggregate(FATALITIES ~ EVTYPE, data = data_raw, FUN = sum)
  data_fatalities_descending <- data_fatalities[order(-data_fatalities$FATALITIES), ]
  bar_fatalities <- ggplot(data = data_fatalities_descending[1:20, ], aes(x = EVTYPE, y = FATALITIES)) + geom_bar(stat = "identity") + theme(axis.text.x=element_text(angle=45, hjust=1)) + labs(title = "TOP 20 EVENTS CAUSING FATALITIES", x = "EVENT TYPE", y = "TOTAL FATALITIES")
  data_injuries <- aggregate(INJURIES ~ EVTYPE, data = data_raw, FUN = sum)
  data_injuries_descending <- data_injuries[order(-data_injuries$INJURIES), ]
  bar_injuries <- ggplot(data = data_injuries_descending[1:20, ], aes(x = EVTYPE, y = INJURIES)) + geom_bar(stat = "identity") + theme(axis.text.x=element_text(angle=45, hjust=1)) + labs(title = "TOP 20 EVENTS CAUSING INJURIES", x = "EVENT TYPE", y = "TOTAL INJURIES")
```

  ```